trigger:
- master

stages:
- stage: Test
  jobs:  
  - job: Test
    timeoutInMinutes: 60

    pool:
      vmImage: 'windows-2019'
    
    strategy:
      matrix:
        custom:
          target: '-target Custom'
      maxParallel: 10
    
    steps:
    - checkout: self
      submodules: true
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: $(target)
        failOnStderr: true
      displayName: $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Publish Test results'