trigger:
- main

stages:
- stage: Aviation
  jobs:  
  - job: Test
    timeoutInMinutes: 240

    pool:
      name: 'default'
    
    strategy:
      matrix:
        domain:
          target: 'CiDomain'
        intranet:
          target: 'CiIntranet'
    
    steps:
    - checkout: self
      submodules: true
    - task: UseDotNet@2
      displayName: 'Use .NET Core 6.0 sdk'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: -target $(target)
        failOnStderr: true
      displayName: Running $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunTitle: $(target)
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Results for $(target)'
