// dummy module for IDE support
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';

import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatBadgeModule } from '@angular/material/badge';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatChipsModule } from '@angular/material/chips';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatDialogModule } from '@angular/material/dialog';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatListModule } from '@angular/material/list';
import { MatMenuModule } from '@angular/material/menu';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatSliderModule } from '@angular/material/slider';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { MatSortModule } from '@angular/material/sort';
import { MatStepperModule } from '@angular/material/stepper';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatToolbarModule } from '@angular/material/toolbar';

import { CalendarModule, DateAdapter } from 'angular-calendar';
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';

import {
  AllorsFocusDirective,
  AllorsBarcodeDirective,
} from '@allors/base/workspace/angular/foundation';

import {
  AllorsMaterialAssociationAutoCompleteComponent,
  AllorsMaterialCancelComponent,
  AllorsMaterialSaveComponent,
  AllorsMaterialAutocompleteComponent,
  AllorsMaterialCheckboxComponent,
  AllorsMaterialChipsComponent,
  AllorsMaterialDatepickerComponent,
  AllorsMaterialDatetimepickerComponent,
  AllorsMaterialFileComponent,
  AllorsMaterialFilesComponent,
  AllorsMaterialInputComponent,
  AllorsMaterialLocalisedMarkdownComponent,
  AllorsMaterialLocalisedTextComponent,
  AllorsMaterialMarkdownComponent,
  AllorsMaterialPaginatorComponent,
  AllorsMaterialRadioGroupComponent,
  AllorsMaterialSelectComponent,
  AllorsMaterialSliderComponent,
  AllorsMaterialSlideToggleComponent,
  AllorsMaterialStaticComponent,
  AllorsMaterialTextareaComponent,
  AllorsMaterialPeriodSelectionToggleComponent,
  AllorsMaterialTableComponent,
} from '@allors/base/workspace/angular-material/foundation';

import {
  AllorsMaterialErrorDialogComponent,
  AllorsMaterialFilterFieldDialogComponent,
  AllorsMaterialFilterFieldSearchComponent,
  AllorsMaterialFilterComponent,
  AllorsMaterialMediaComponent,
  AllorMediaPreviewComponent,
  AllorsMaterialBarcodeEntryComponent,
  AllorsMaterialSideMenuComponent,
  AllorsMaterialSideNavToggleComponent,
  FactoryFabComponent,
  AllorsMaterialDynamicCreateComponent,
  AllorsMaterialDynamicEditComponent,
  AllorsMaterialDynamicEditDetailPanelComponent,
  AllorsMaterialDynamicEditExtentPanelComponent,
  AllorsMaterialDynamicSummaryPanelComponent,
  AllorsMaterialDynamicViewDetailPanelComponent,
  AllorsMaterialDynamicViewExtentPanelComponent,
} from '@allors/base/workspace/angular-material/application';

import {
  BasepriceFormComponent,
  BrandListPageComponent,
  CarrierFormComponent,
  CarrierListPageComponent,
  CommunicationEventListPageComponent,
  ContactMechanismInlineComponent,
  CustomerRelationshipFormComponent,
  CustomerShipmentCreateFormComponent,
  CustomerShipmentEditFormComponent,
  CustomerShipmentOverviewPageComponent,
  CustomerShipmentSummaryPanelComponent,
  DisbursementFormComponent,
  EmailAddressCreateFormComponent,
  EmailAddressEditFormComponent,
  EmailCommunicationFormComponent,
  EmploymentFormComponent,
  ExchangeRateFormComponent,
  ExchangeRateListPageComponent,
  FaceToFaceCommunicationFormComponent,
  FacilityInlineComponent,
  GoodListPageComponent,
  InlineBrandComponent,
  InlineModelComponent,
  InlineWebAddressComponent,
  InventoryItemTransactionCreateFormComponent,
  LetterCorrespondenceFormComponent,
  NonUnifiedGoodCreateFormComponent,
  NonUnifiedGoodEditFormComponent,
  NonUnifiedGoodOverviewPageComponent,
  NonUnifiedGoodSummaryPanelComponent,
  NonUnifiedPartInlineComponent,
  NotificationLinkComponent,
  NotificationListPageComponent,
  OrderAdjustmentFormComponent,
  OrganisationContactRelationshipFormComponent,
  OrganisationInlineComponent,
  OrganisationSummaryPanelComponent,
  PartCategoryFormComponent,
  PartCategoryListPageComponent,
  PartListPageComponent,
  PartyContactMechanismEmailAddressInlineComponent,
  PartyContactmechanismFormComponent,
  PartyContactMechanismPostalAddressInlineComponent,
  PartyContactMechanismTelecommunicationsNumberInlineComponent,
  PartyInlineComponent,
  PartyRateFormComponent,
  PersonInlineComponent,
  PersonSummaryPanelComponent,
  PhoneCommunicationFormComponent,
  PositionTypeFormComponent,
  PositionTypeRateFormComponent,
  PositionTypeRateListPageComponent,
  PositionTypesListPageComponent,
  PostalAddressCreateFormComponent,
  PostalAddressEditFormComponent,
  PostalAddressInlineComponent,
  ProductIdentificationFormComponent,
  ProductQuoteApprovalFormComponent,
  ProductQuoteEditFormComponent,
  ProductQuoteListPageComponent,
  ProductQuoteSummaryPanelComponent,
  ProductTypeFormComponent,
  ProductTypesOverviewPageComponent,
  PurchaseInvoiceApprovalFormComponent,
  PurchaseInvoiceCreateFormComponent,
  PurchaseInvoiceEditFormComponent,
  PurchaseInvoiceListPageComponent,
  PurchaseOrderApprovalLevel1FormComponent,
  PurchaseOrderApprovalLevel2FormComponent,
  PurchaseOrderEditFormComponent,
  PurchaseOrderListPageComponent,
  PurchaseReturnCreateFormComponent,
  PurchaseReturnEditFormComponent,
  PurchaseShipmentCreateFormComponent,
  PurchaseShipmentEditFormComponent,
  PurchaseShipmentOverviewPageComponent,
  PurchaseShipmentSummaryPanelComponent,
  PurchasInvoiceSummaryPanelComponent,
  ReceiptFormComponent,
  RepeatingPurchaseInvoiceFormComponent,
  RepeatingSalesInvoiceFormComponent,
  RequestForQuoteCreateFormComponent,
  RequestForQuoteEditFormComponent,
  RequestForQuoteListPageComponent,
  RequestForQuoteOverviewPageComponent,
  RequestForQuoteSummaryPanelComponent,
  RequestItemFormComponent,
  SalesInvoiceListPageComponent,
  SalesInvoiceSummaryPanelComponent,
  SalesOrderEditFormComponent,
  SalesOrderListPageComponent,
  SalesOrderSummaryPanelComponent,
  SalesTermFormComponent,
  SelectInternalOrganisationComponent,
  SerialisedItemCharacteristicListPageComponent,
  SerialisedItemCharacteristicTypeFormComponent,
  SerialisedItemSummaryPanelComponent,
  ShipmentItemFormComponent,
  ShipmentListPageComponent,
  SubContractorRelationshipFormComponent,
  SupplierOfferingFormComponent,
  SupplierRelationshipFormComponent,
  TaskAssignmentLinkComponent,
  TaskAssignmentListPageComponent,
  TelecommunicationsNumberCreateFormComponent,
  TelecommunicationsNumberEditFormComponent,
  UnifiedGoodListPageComponent,
  UnifiedGoodSummaryPanelComponent,
  UserProfileFormComponent,
  UserProfileLinkComponent,
  WebAddressCreateFormComponent,
  WebAddressEditFormComponent,
  WorkEffortAssignmentRateFormComponent,
  WorkEffortInvoiceItemAssignmentFormComponent,
  WorkEffortPartyAssignmentFormComponent,
  WorkRequirementCreateFormComponent,
  WorkRequirementEditFormComponent,
  WorkRequirementOverviewPageComponent,
  WorkRequirementSummaryPanelComponent,
} from '@allors/apps-intranet/workspace/angular-material';

import {
  BrandFormComponent,
  CatalogueFormComponent,
  CataloguesListPageComponent,
  FacilityFormComponent,
  MaintenanceAgreementCreateFormComponent,
  MaintenanceAgreementEditFormComponent,
  MaintenanceAgreementListPageComponent,
  MaintenanceAgreementOverviewPageComponent,
  MaintenanceAgreementSummaryPanelComponent,
  NonSerialisedInventoryItemFormComponent,
  NonUnifiedPartCreateFormComponent,
  NonUnifiedPartEditFormComponent,
  NonUnifiedPartListPageComponent,
  NonUnifiedPartOverviewPageComponent,
  NonUnifiedPartSummaryPanelComponent,
  OperatingHoursTransactionFormComponent,
  OrganisationCreateFormComponent,
  OrganisationEditFormComponent,
  OrganisationListPageComponent,
  OrganisationOverviewPageComponent,
  PersonFormComponent,
  PersonListPageComponent,
  PersonOverviewPageComponent,
  ProductCategoryFormComponent,
  ProductCategoryListPageComponent,
  ProductQuoteCreateFormComponent,
  ProductQuoteOverviewPageComponent,
  PurchaseInvoiceItemFormComponent,
  PurchaseInvoiceOverviewPageComponent,
  PurchaseInvoicePanelEditComponent,
  PurchaseInvoicePanelViewComponent,
  PurchaseOrderCreateFormComponent,
  PurchaseOrderItemFormComponent,
  PurchaseOrderOverviewPageComponent,
  PurchaseOrderSummaryPanelComponent,
  QuoteItemFormComponent,
  RedirectComponent,
  SalesInvoiceCreateFormComponent,
  SalesInvoiceEditFormComponent,
  SalesInvoiceItemFormComponent,
  SalesInvoiceOverviewPageComponent,
  SalesOrderCreateFormComponent,
  SalesOrderItemFormComponent,
  SalesOrderOverviewPageComponent,
  SchedulerComponent,
  SerialisedInventoryItemFormComponent,
  SerialisedItemCreateFormComponent,
  SerialisedItemEditFormComponent,
  SerialisedItemListPageComponent,
  SerialisedItemOverviewPageComponent,
  SettingsFormComponent,
  SettingsListPageComponent,
  ShopfloorAppComponent,
  TimeEntryFormComponent,
  TimesheetAppComponent,
  UnifiedGoodCreateFormComponent,
  UnifiedGoodEditFormComponent,
  UnifiedGoodOverviewPageComponent,
  VehicleFormComponent,
  VehicleInlineComponent,
  VehicleListPageComponent,
  VehicleOverviewPageComponent,
  VehicleSummaryPanelComponent,
  WorkEffortFixedAssetAssignmentFormComponent,
  WorkEffortInventoryAssignmentFormComponent,
  WorkEffortListPageComponent,
  WorkEffortPartStandardFormComponent,
  WorkEffortPurchaseOrderItemAssignmentFormComponent,
  WorkEffortTypeCreateFormComponent,
  WorkEffortTypeEditFormComponent,
  WorkEffortTypeListPageComponent,
  WorkEffortTypeOverviewPageComponent,
  WorkEffortTypeSummaryPanelComponent,
  WorkRequirementFulfillmentCreateFormComponent,
  WorkRequirementListPageComponent,
  WorkTaskCreateFormComponent,
  WorkTaskEditFormComponent,
  WorkTaskOverviewPageComponent,
  WorkTaskSummaryPanelComponent,
} from '@allors/aviation-intranet/workspace/angular-material';

import { DummyComponent } from './index';

@NgModule({
  declarations: [
    // Base Foundation
    AllorsFocusDirective,
    AllorsBarcodeDirective,
    // Base Material Foundation
    AllorsMaterialAssociationAutoCompleteComponent,
    AllorsMaterialCancelComponent,
    AllorsMaterialSaveComponent,
    AllorsMaterialAutocompleteComponent,
    AllorsMaterialCheckboxComponent,
    AllorsMaterialChipsComponent,
    AllorsMaterialDatepickerComponent,
    AllorsMaterialDatetimepickerComponent,
    AllorsMaterialFileComponent,
    AllorsMaterialFilesComponent,
    AllorsMaterialInputComponent,
    AllorsMaterialLocalisedMarkdownComponent,
    AllorsMaterialLocalisedTextComponent,
    AllorsMaterialMarkdownComponent,
    AllorsMaterialPaginatorComponent,
    AllorsMaterialRadioGroupComponent,
    AllorsMaterialSelectComponent,
    AllorsMaterialSliderComponent,
    AllorsMaterialSlideToggleComponent,
    AllorsMaterialStaticComponent,
    AllorsMaterialTextareaComponent,
    AllorsMaterialPeriodSelectionToggleComponent,
    AllorsMaterialTableComponent,
    // Base Material Application
    AllorsMaterialErrorDialogComponent,
    AllorsMaterialFilterFieldDialogComponent,
    AllorsMaterialFilterFieldSearchComponent,
    AllorsMaterialFilterComponent,
    AllorsMaterialMediaComponent,
    AllorMediaPreviewComponent,
    AllorsMaterialBarcodeEntryComponent,
    AllorsMaterialSideMenuComponent,
    AllorsMaterialSideNavToggleComponent,
    FactoryFabComponent,
    AllorsMaterialDynamicCreateComponent,
    AllorsMaterialDynamicEditComponent,
    AllorsMaterialDynamicEditDetailPanelComponent,
    AllorsMaterialDynamicEditExtentPanelComponent,
    AllorsMaterialDynamicSummaryPanelComponent,
    AllorsMaterialDynamicViewDetailPanelComponent,
    AllorsMaterialDynamicViewExtentPanelComponent,
    // Intranet Material
    BasepriceFormComponent,
    BrandFormComponent,
    BrandListPageComponent,
    CarrierFormComponent,
    CarrierListPageComponent,
    CatalogueFormComponent,
    CataloguesListPageComponent,
    CommunicationEventListPageComponent,
    ContactMechanismInlineComponent,
    CustomerRelationshipFormComponent,
    CustomerShipmentCreateFormComponent,
    CustomerShipmentEditFormComponent,
    CustomerShipmentOverviewPageComponent,
    CustomerShipmentSummaryPanelComponent,
    DisbursementFormComponent,
    EmailAddressCreateFormComponent,
    EmailAddressEditFormComponent,
    EmailCommunicationFormComponent,
    EmploymentFormComponent,
    ExchangeRateFormComponent,
    ExchangeRateListPageComponent,
    FaceToFaceCommunicationFormComponent,
    FacilityFormComponent,
    FacilityInlineComponent,
    GoodListPageComponent,
    InlineBrandComponent,
    InlineModelComponent,
    InlineWebAddressComponent,
    InventoryItemTransactionCreateFormComponent,
    LetterCorrespondenceFormComponent,
    MaintenanceAgreementCreateFormComponent,
    MaintenanceAgreementEditFormComponent,
    MaintenanceAgreementListPageComponent,
    MaintenanceAgreementOverviewPageComponent,
    MaintenanceAgreementSummaryPanelComponent,
    NonSerialisedInventoryItemFormComponent,
    NonUnifiedGoodCreateFormComponent,
    NonUnifiedGoodEditFormComponent,
    NonUnifiedGoodOverviewPageComponent,
    NonUnifiedGoodSummaryPanelComponent,
    NonUnifiedPartCreateFormComponent,
    NonUnifiedPartEditFormComponent,
    NonUnifiedPartInlineComponent,
    NonUnifiedPartListPageComponent,
    NonUnifiedPartOverviewPageComponent,
    NonUnifiedPartSummaryPanelComponent,
    NotificationLinkComponent,
    NotificationListPageComponent,
    OperatingHoursTransactionFormComponent,
    OrderAdjustmentFormComponent,
    OrganisationContactRelationshipFormComponent,
    OrganisationCreateFormComponent,
    OrganisationEditFormComponent,
    OrganisationInlineComponent,
    OrganisationListPageComponent,
    OrganisationOverviewPageComponent,
    OrganisationSummaryPanelComponent,
    PartCategoryFormComponent,
    PartCategoryListPageComponent,
    PartListPageComponent,
    PartyContactMechanismEmailAddressInlineComponent,
    PartyContactmechanismFormComponent,
    PartyContactMechanismPostalAddressInlineComponent,
    PartyContactMechanismTelecommunicationsNumberInlineComponent,
    PartyInlineComponent,
    PartyRateFormComponent,
    PersonFormComponent,
    PersonInlineComponent,
    PersonListPageComponent,
    PersonOverviewPageComponent,
    PersonSummaryPanelComponent,
    PhoneCommunicationFormComponent,
    PositionTypeFormComponent,
    PositionTypeRateFormComponent,
    PositionTypeRateListPageComponent,
    PositionTypesListPageComponent,
    PostalAddressCreateFormComponent,
    PostalAddressEditFormComponent,
    PostalAddressInlineComponent,
    ProductCategoryFormComponent,
    ProductCategoryListPageComponent,
    ProductIdentificationFormComponent,
    ProductQuoteApprovalFormComponent,
    ProductQuoteCreateFormComponent,
    ProductQuoteEditFormComponent,
    ProductQuoteListPageComponent,
    ProductQuoteOverviewPageComponent,
    ProductQuoteSummaryPanelComponent,
    ProductTypeFormComponent,
    ProductTypesOverviewPageComponent,
    PurchaseInvoiceApprovalFormComponent,
    PurchaseInvoiceCreateFormComponent,
    PurchaseInvoiceEditFormComponent,
    PurchaseInvoiceItemFormComponent,
    PurchaseInvoiceListPageComponent,
    PurchaseInvoiceOverviewPageComponent,
    PurchaseInvoicePanelEditComponent,
    PurchaseInvoicePanelViewComponent,
    PurchaseOrderApprovalLevel1FormComponent,
    PurchaseOrderApprovalLevel2FormComponent,
    PurchaseOrderCreateFormComponent,
    PurchaseOrderEditFormComponent,
    PurchaseOrderItemFormComponent,
    PurchaseOrderListPageComponent,
    PurchaseOrderOverviewPageComponent,
    PurchaseOrderSummaryPanelComponent,
    PurchaseReturnCreateFormComponent,
    PurchaseReturnEditFormComponent,
    PurchaseShipmentCreateFormComponent,
    PurchaseShipmentEditFormComponent,
    PurchaseShipmentOverviewPageComponent,
    PurchaseShipmentSummaryPanelComponent,
    PurchasInvoiceSummaryPanelComponent,
    QuoteItemFormComponent,
    ReceiptFormComponent,
    RedirectComponent,
    RepeatingPurchaseInvoiceFormComponent,
    RepeatingSalesInvoiceFormComponent,
    RequestForQuoteCreateFormComponent,
    RequestForQuoteEditFormComponent,
    RequestForQuoteListPageComponent,
    RequestForQuoteOverviewPageComponent,
    RequestForQuoteSummaryPanelComponent,
    RequestItemFormComponent,
    SalesInvoiceCreateFormComponent,
    SalesInvoiceEditFormComponent,
    SalesInvoiceItemFormComponent,
    SalesInvoiceListPageComponent,
    SalesInvoiceOverviewPageComponent,
    SalesInvoiceSummaryPanelComponent,
    SalesOrderCreateFormComponent,
    SalesOrderCreateFormComponent,
    SalesOrderEditFormComponent,
    SalesOrderItemFormComponent,
    SalesOrderListPageComponent,
    SalesOrderOverviewPageComponent,
    SalesOrderSummaryPanelComponent,
    SalesTermFormComponent,
    SchedulerComponent,
    SelectInternalOrganisationComponent,
    SerialisedInventoryItemFormComponent,
    SerialisedItemCharacteristicListPageComponent,
    SerialisedItemCharacteristicTypeFormComponent,
    SerialisedItemCreateFormComponent,
    SerialisedItemEditFormComponent,
    SerialisedItemListPageComponent,
    SerialisedItemOverviewPageComponent,
    SerialisedItemSummaryPanelComponent,
    SettingsFormComponent,
    SettingsListPageComponent,
    ShipmentItemFormComponent,
    ShipmentListPageComponent,
    ShopfloorAppComponent,
    SubContractorRelationshipFormComponent,
    SupplierOfferingFormComponent,
    SupplierRelationshipFormComponent,
    TaskAssignmentLinkComponent,
    TaskAssignmentListPageComponent,
    TelecommunicationsNumberCreateFormComponent,
    TelecommunicationsNumberEditFormComponent,
    TimeEntryFormComponent,
    TimesheetAppComponent,
    UnifiedGoodCreateFormComponent,
    UnifiedGoodEditFormComponent,
    UnifiedGoodListPageComponent,
    UnifiedGoodOverviewPageComponent,
    UnifiedGoodSummaryPanelComponent,
    UserProfileFormComponent,
    UserProfileLinkComponent,
    VehicleFormComponent,
    VehicleInlineComponent,
    VehicleListPageComponent,
    VehicleOverviewPageComponent,
    VehicleSummaryPanelComponent,
    WebAddressCreateFormComponent,
    WebAddressEditFormComponent,
    WorkEffortAssignmentRateFormComponent,
    WorkEffortFixedAssetAssignmentFormComponent,
    WorkEffortInventoryAssignmentFormComponent,
    WorkEffortInvoiceItemAssignmentFormComponent,
    WorkEffortListPageComponent,
    WorkEffortPartStandardFormComponent,
    WorkEffortPartyAssignmentFormComponent,
    WorkEffortPurchaseOrderItemAssignmentFormComponent,
    WorkEffortTypeCreateFormComponent,
    WorkEffortTypeEditFormComponent,
    WorkEffortTypeListPageComponent,
    WorkEffortTypeOverviewPageComponent,
    WorkEffortTypeSummaryPanelComponent,
    WorkRequirementCreateFormComponent,
    WorkRequirementEditFormComponent,
    WorkRequirementFulfillmentCreateFormComponent,
    WorkRequirementListPageComponent,
    WorkRequirementOverviewPageComponent,
    WorkRequirementSummaryPanelComponent,
    WorkTaskCreateFormComponent,
    WorkTaskEditFormComponent,
    WorkTaskOverviewPageComponent,
    WorkTaskSummaryPanelComponent,
  ],
  imports: [
    BrowserModule,
    RouterModule,
    NoopAnimationsModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatPaginatorModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTabsModule,
    MatTableModule,
    MatToolbarModule,
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }),
  ],
})
export class AppModule {}
