import { M } from '@allors/default/workspace/meta';
import { IObject, IRule } from '@allors/system/workspace/domain';
import {
  EmailAddressDisplayNameRule,
  InventoryItemFacilityNameRule,
  OrganisationDisplayAddress2Rule,
  OrganisationDisplayAddress3Rule,
  OrganisationDisplayAddressRule,
  OrganisationDisplayClassificationRule,
  OrganisationDisplayNameRule,
  PartyDisplayPhoneRule,
  PersonDisplayEmailRule,
  PersonDisplayNameRule,
  PostalAddressDisplayNameRule,
  PurchaseInvoiceItemTotalIncVatRule,
  PurchaseInvoiceItemUnitVatRule,
  PurchaseOrderItemTotalIncVatRule,
  PurchaseOrderItemUnitVatRule,
  SerialisedItemAgeRule,
  SerialisedItemYearsToGoRule,
  TelecommunicationsNumberDisplayNameRule,
  WebAddressDisplayNameRule,
  WorkEffortInventoryAssignmentTotalSellingPriceRule,
} from '@allors/apps-intranet/workspace/derivations';

import {
  IataGseCodeDisplayNameRule,
  MaintenanceAgreementDisplayNameRule,
  NonSerialisedInventoryItemPartDisplayNameRule,
  NonSerialisedInventoryItemDutchPartDisplayNameRule,
  NonSerialisedInventoryItemSpanishPartDisplayNameRule,
  NonUnifiedPartExternalSellingPriceRule,
  NonUnifiedPartInternalSellingPriceRule,
  OperatingHoursTransactionDeltaRule,
  OperatingHoursTransactionDaysRule,
  QuoteItemTotalIncVatRule,
  QuoteItemUnitVatRule,
  SalesInvoiceItemTotalIncVatRule,
  SalesInvoiceItemUnitVatRule,
  SalesOrderItemTotalIncVatRule,
  SalesOrderItemUnitVatRule,
  SerialisedInventoryItemDisplayNameRule,
  SerialisedItemGrossBookValueRule,
  SerialisedItemExpectedPosaRule,
  SerialisedItemGoingConcernRule,
  SerialisedItemActualGrossBookValueRule,
  SerialisedItemMarketValueRule,
  VehicleDisplayNameRule,
  WorkEffortPartStandardPartDisplayNameRule,
  WorkEffortTypeDisplayNameRule,
} from '@allors/aviation-intranet/workspace/derivations';

export function ruleBuilder(m: M): IRule<IObject>[] {
  return [
    new EmailAddressDisplayNameRule(m),
    new InventoryItemFacilityNameRule(m),
    new OrganisationDisplayAddressRule(m),
    new OrganisationDisplayAddress2Rule(m),
    new OrganisationDisplayAddress3Rule(m),
    new OrganisationDisplayClassificationRule(m),
    new OrganisationDisplayNameRule(m),
    new PartyDisplayPhoneRule(m),
    new PersonDisplayEmailRule(m),
    new PersonDisplayNameRule(m),
    new PostalAddressDisplayNameRule(m),
    new PurchaseInvoiceItemTotalIncVatRule(m),
    new PurchaseInvoiceItemUnitVatRule(m),
    new PurchaseOrderItemTotalIncVatRule(m),
    new PurchaseOrderItemUnitVatRule(m),
    new SerialisedItemAgeRule(m),
    new SerialisedItemYearsToGoRule(m),
    new TelecommunicationsNumberDisplayNameRule(m),
    new WebAddressDisplayNameRule(m),
    new WorkEffortInventoryAssignmentTotalSellingPriceRule(m),

    // Custom
    new IataGseCodeDisplayNameRule(m),
    new NonSerialisedInventoryItemPartDisplayNameRule(m),
    new NonSerialisedInventoryItemDutchPartDisplayNameRule(m),
    new NonSerialisedInventoryItemSpanishPartDisplayNameRule(m),
    new NonUnifiedPartExternalSellingPriceRule(m),
    new NonUnifiedPartInternalSellingPriceRule(m),
    new MaintenanceAgreementDisplayNameRule(m),
    new OperatingHoursTransactionDaysRule(m),
    new OperatingHoursTransactionDeltaRule(m),
    new OperatingHoursTransactionDeltaRule(m),
    new QuoteItemTotalIncVatRule(m),
    new QuoteItemUnitVatRule(m),
    new SalesInvoiceItemTotalIncVatRule(m),
    new SalesInvoiceItemUnitVatRule(m),
    new SalesOrderItemTotalIncVatRule(m),
    new SalesOrderItemUnitVatRule(m),
    new SerialisedInventoryItemDisplayNameRule(m),
    new SerialisedItemGrossBookValueRule(m),
    new SerialisedItemExpectedPosaRule(m),
    new SerialisedItemGoingConcernRule(m),
    new SerialisedItemActualGrossBookValueRule(m),
    new SerialisedItemMarketValueRule(m),
    new VehicleDisplayNameRule(m),
    new WorkEffortPartStandardPartDisplayNameRule(m),
    new WorkEffortTypeDisplayNameRule(m),
  ];
}
