// dummy module for IDE support
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule } from '@angular/common/http';

import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatBadgeModule } from '@angular/material/badge';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatChipsModule } from '@angular/material/chips';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatDialogModule } from '@angular/material/dialog';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatListModule } from '@angular/material/list';
import { MatMenuModule } from '@angular/material/menu';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatSliderModule } from '@angular/material/slider';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { MatSortModule } from '@angular/material/sort';
import { MatStepperModule } from '@angular/material/stepper';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatToolbarModule } from '@angular/material/toolbar';

import {
  AllorsFocusDirective,
  AllorsBarcodeDirective,
  ThrottledDirective,
} from '@allors/base/workspace/angular/foundation';

import {
  AllorsMaterialAssociationAutoCompleteComponent,
  AllorsMaterialCancelComponent,
  AllorsMaterialSaveComponent,
  AllorsMaterialAutocompleteComponent,
  AllorsMaterialCheckboxComponent,
  AllorsMaterialChipsComponent,
  AllorsMaterialDatepickerComponent,
  AllorsMaterialDatetimepickerComponent,
  AllorsMaterialFileComponent,
  AllorsMaterialFilesComponent,
  AllorsMaterialInputComponent,
  AllorsMaterialLocalisedMarkdownComponent,
  AllorsMaterialLocalisedTextComponent,
  AllorsMaterialMarkdownComponent,
  AllorsMaterialPaginatorComponent,
  AllorsMaterialRadioGroupComponent,
  AllorsMaterialSelectComponent,
  AllorsMaterialSliderComponent,
  AllorsMaterialSlideToggleComponent,
  AllorsMaterialStaticComponent,
  AllorsMaterialTextareaComponent,
  AllorsMaterialPeriodSelectionToggleComponent,
  AllorsMaterialTableComponent,
} from '@allors/base/workspace/angular-material/foundation';

import {
  AllorsMaterialErrorDialogComponent,
  AllorsMaterialFilterFieldDialogComponent,
  AllorsMaterialFilterFieldSearchComponent,
  AllorsMaterialFilterComponent,
  AllorsMaterialMediaComponent,
  AllorMediaPreviewComponent,
  AllorsMaterialBarcodeEntryComponent,
  AllorsMaterialSideMenuComponent,
  AllorsMaterialSideNavToggleComponent,
  FactoryFabComponent,
  AllorsMaterialDynamicCreateComponent,
  AllorsMaterialDynamicEditComponent,
  AllorsMaterialDynamicEditDetailPanelComponent,
  AllorsMaterialDynamicEditExtentPanelComponent,
  AllorsMaterialDynamicSummaryPanelComponent,
  AllorsMaterialDynamicViewDetailPanelComponent,
  AllorsMaterialDynamicViewExtentPanelComponent,
} from '@allors/base/workspace/angular-material/application';

import {
  BankAccountFormComponent,
  BankInlineComponent,
  BasepriceFormComponent,
  BrandListPageComponent,
  CarrierFormComponent,
  CarrierListPageComponent,
  CommunicationEventListPageComponent,
  ContactMechanismInlineComponent,
  CustomerRelationshipFormComponent,
  CustomerShipmentCreateFormComponent,
  CustomerShipmentEditFormComponent,
  CustomerShipmentOverviewPageComponent,
  CustomerShipmentSummaryPanelComponent,
  DisbursementFormComponent,
  EmailAddressCreateFormComponent,
  EmailAddressEditFormComponent,
  EmailCommunicationFormComponent,
  EmailMessageFormComponent,
  EmailMessageListPageComponent,
  EmploymentFormComponent,
  ExchangeRateFormComponent,
  ExchangeRateListPageComponent,
  FaceToFaceCommunicationFormComponent,
  FacilityInlineComponent,
  FacilityListPageComponent,
  GoodListPageComponent,
  InlineBrandComponent,
  InlineModelComponent,
  InlineWebAddressComponent,
  InventoryItemTransactionCreateFormComponent,
  LetterCorrespondenceFormComponent,
  ModelListPageComponent,
  NonUnifiedGoodCreateFormComponent,
  NonUnifiedGoodEditFormComponent,
  NonUnifiedGoodOverviewPageComponent,
  NonUnifiedGoodSummaryPanelComponent,
  NonUnifiedPartInlineComponent,
  NotificationLinkComponent,
  NotificationListPageComponent,
  OrderAdjustmentFormComponent,
  OrganisationContactRelationshipFormComponent,
  OrganisationInlineComponent,
  OrganisationSummaryPanelComponent,
  PartCategoryFormComponent,
  PartCategoryListPageComponent,
  PartListPageComponent,
  PartyContactMechanismEmailAddressInlineComponent,
  PartyContactmechanismFormComponent,
  PartyContactMechanismPostalAddressInlineComponent,
  PartyContactMechanismTelecommunicationsNumberInlineComponent,
  PartyInlineComponent,
  PartyRateFormComponent,
  PaymentPanelEditComponent,
  PaymentPanelViewComponent,
  PersonInlineComponent,
  PersonSummaryPanelComponent,
  PhoneCommunicationFormComponent,
  PositionTypeFormComponent,
  PositionTypeRateFormComponent,
  PositionTypeRateListPageComponent,
  PositionTypesListPageComponent,
  PostalAddressCreateFormComponent,
  PostalAddressEditFormComponent,
  PostalAddressInlineComponent,
  ProductIdentificationFormComponent,
  ProductQuoteApprovalFormComponent,
  ProductQuoteEditFormComponent,
  ProductQuoteListPageComponent,
  ProductQuoteSummaryPanelComponent,
  ProductTypeFormComponent,
  ProductTypesOverviewPageComponent,
  PurchaseInvoiceApprovalFormComponent,
  PurchaseInvoiceCreateFormComponent,
  PurchaseInvoiceEditFormComponent,
  PurchaseInvoiceListPageComponent,
  PurchaseOrderApprovalLevel1FormComponent,
  PurchaseOrderApprovalLevel2FormComponent,
  PurchaseOrderEditFormComponent,
  PurchaseOrderInvoicePanelEditComponent,
  PurchaseOrderInvoicePanelViewComponent,
  PurchaseOrderListPageComponent,
  PurchaseReturnCreateFormComponent,
  PurchaseReturnEditFormComponent,
  PurchaseReturnOverviewPageComponent,
  PurchaseReturnSummaryPanelComponent,
  PurchaseShipmentCreateFormComponent,
  PurchaseShipmentEditFormComponent,
  PurchaseShipmentOverviewPageComponent,
  PurchaseShipmentSummaryPanelComponent,
  PurchasInvoiceSummaryPanelComponent,
  ReceiptFormComponent,
  RepeatingPurchaseInvoiceFormComponent,
  RepeatingSalesInvoiceFormComponent,
  RepeatingSalesInvoicePanelEditComponent,
  RepeatingSalesInvoicePanelViewComponent,
  RequestForQuoteCreateFormComponent,
  RequestForQuoteEditFormComponent,
  RequestForQuoteListPageComponent,
  RequestForQuoteOverviewPageComponent,
  RequestForQuoteSummaryPanelComponent,
  RequestItemFormComponent,
  SalesInvoiceListPageComponent,
  SalesInvoiceSummaryPanelComponent,
  SalesOrderEditFormComponent,
  SalesOrderListPageComponent,
  SalesOrderSummaryPanelComponent,
  SalesTermFormComponent,
  SelectInternalOrganisationComponent,
  SerialisedItemCharacteristicListPageComponent,
  SerialisedItemCharacteristicTypeFormComponent,
  SerialisedItemSummaryPanelComponent,
  ShipmentItemFormComponent,
  ShipmentListPageComponent,
  SubContractorRelationshipFormComponent,
  SupplierOfferingFormComponent,
  SupplierRelationshipFormComponent,
  TaskAssignmentLinkComponent,
  TaskAssignmentListPageComponent,
  TelecommunicationsNumberCreateFormComponent,
  UnifiedGoodListPageComponent,
  UnifiedGoodSummaryPanelComponent,
  UserProfileFormComponent,
  UserProfileLinkComponent,
  WebAddressCreateFormComponent,
  WebAddressEditFormComponent,
  WorkEffortAssignmentRateFormComponent,
  WorkEffortInvoiceItemAssignmentFormComponent,
  WorkEffortPartyAssignmentFormComponent,
  WorkRequirementCreateFormComponent,
  WorkRequirementEditFormComponent,
  WorkRequirementOverviewPageComponent,
  WorkRequirementSummaryPanelComponent,
} from './index';

@NgModule({
  declarations: [
    // Base Foundation
    AllorsFocusDirective,
    AllorsBarcodeDirective,
    ThrottledDirective,
    // Base Material Foundation
    AllorsMaterialAssociationAutoCompleteComponent,
    AllorsMaterialCancelComponent,
    AllorsMaterialSaveComponent,
    AllorsMaterialAutocompleteComponent,
    AllorsMaterialCheckboxComponent,
    AllorsMaterialChipsComponent,
    AllorsMaterialDatepickerComponent,
    AllorsMaterialDatetimepickerComponent,
    AllorsMaterialFileComponent,
    AllorsMaterialFilesComponent,
    AllorsMaterialInputComponent,
    AllorsMaterialLocalisedMarkdownComponent,
    AllorsMaterialLocalisedTextComponent,
    AllorsMaterialMarkdownComponent,
    AllorsMaterialPaginatorComponent,
    AllorsMaterialRadioGroupComponent,
    AllorsMaterialSelectComponent,
    AllorsMaterialSliderComponent,
    AllorsMaterialSlideToggleComponent,
    AllorsMaterialStaticComponent,
    AllorsMaterialTextareaComponent,
    AllorsMaterialPeriodSelectionToggleComponent,
    AllorsMaterialTableComponent,
    // Base Material Application
    AllorsMaterialErrorDialogComponent,
    AllorsMaterialFilterFieldDialogComponent,
    AllorsMaterialFilterFieldSearchComponent,
    AllorsMaterialFilterComponent,
    AllorsMaterialMediaComponent,
    AllorMediaPreviewComponent,
    AllorsMaterialBarcodeEntryComponent,
    AllorsMaterialSideMenuComponent,
    AllorsMaterialSideNavToggleComponent,
    FactoryFabComponent,
    AllorsMaterialDynamicCreateComponent,
    AllorsMaterialDynamicEditComponent,
    AllorsMaterialDynamicEditDetailPanelComponent,
    AllorsMaterialDynamicEditExtentPanelComponent,
    AllorsMaterialDynamicSummaryPanelComponent,
    AllorsMaterialDynamicViewDetailPanelComponent,
    AllorsMaterialDynamicViewExtentPanelComponent,
    // Intranet Material
    BankAccountFormComponent,
    BankInlineComponent,
    BasepriceFormComponent,
    BrandListPageComponent,
    CarrierFormComponent,
    CarrierListPageComponent,
    CommunicationEventListPageComponent,
    ContactMechanismInlineComponent,
    CustomerRelationshipFormComponent,
    CustomerShipmentCreateFormComponent,
    CustomerShipmentEditFormComponent,
    CustomerShipmentOverviewPageComponent,
    CustomerShipmentSummaryPanelComponent,
    DisbursementFormComponent,
    EmailAddressCreateFormComponent,
    EmailAddressEditFormComponent,
    EmailCommunicationFormComponent,
    EmailMessageFormComponent,
    EmailMessageListPageComponent,
    EmploymentFormComponent,
    ExchangeRateFormComponent,
    ExchangeRateListPageComponent,
    FaceToFaceCommunicationFormComponent,
    FacilityInlineComponent,
    FacilityListPageComponent,
    GoodListPageComponent,
    InlineBrandComponent,
    InlineModelComponent,
    InlineWebAddressComponent,
    InventoryItemTransactionCreateFormComponent,
    LetterCorrespondenceFormComponent,
    ModelListPageComponent,
    NonUnifiedGoodCreateFormComponent,
    NonUnifiedGoodEditFormComponent,
    NonUnifiedGoodOverviewPageComponent,
    NonUnifiedGoodSummaryPanelComponent,
    NonUnifiedPartInlineComponent,
    NotificationLinkComponent,
    NotificationListPageComponent,
    OrderAdjustmentFormComponent,
    OrganisationContactRelationshipFormComponent,
    OrganisationInlineComponent,
    OrganisationSummaryPanelComponent,
    PartCategoryFormComponent,
    PartCategoryListPageComponent,
    PartListPageComponent,
    PartyContactMechanismEmailAddressInlineComponent,
    PartyContactmechanismFormComponent,
    PartyContactMechanismPostalAddressInlineComponent,
    PartyContactMechanismTelecommunicationsNumberInlineComponent,
    PartyInlineComponent,
    PartyRateFormComponent,
    PaymentPanelEditComponent,
    PaymentPanelViewComponent,
    PersonInlineComponent,
    PersonSummaryPanelComponent,
    PhoneCommunicationFormComponent,
    PositionTypeFormComponent,
    PositionTypeRateFormComponent,
    PositionTypeRateListPageComponent,
    PositionTypesListPageComponent,
    PostalAddressCreateFormComponent,
    PostalAddressEditFormComponent,
    PostalAddressInlineComponent,
    ProductIdentificationFormComponent,
    ProductQuoteApprovalFormComponent,
    ProductQuoteEditFormComponent,
    ProductQuoteListPageComponent,
    ProductQuoteSummaryPanelComponent,
    ProductTypeFormComponent,
    ProductTypesOverviewPageComponent,
    PurchaseInvoiceApprovalFormComponent,
    PurchaseInvoiceCreateFormComponent,
    PurchaseInvoiceEditFormComponent,
    PurchaseInvoiceListPageComponent,
    PurchaseOrderApprovalLevel1FormComponent,
    PurchaseOrderApprovalLevel2FormComponent,
    PurchaseOrderEditFormComponent,
    PurchaseOrderInvoicePanelEditComponent,
    PurchaseOrderInvoicePanelViewComponent,
    PurchaseOrderListPageComponent,
    PurchaseReturnCreateFormComponent,
    PurchaseReturnEditFormComponent,
    PurchaseReturnOverviewPageComponent,
    PurchaseReturnSummaryPanelComponent,
    PurchaseShipmentCreateFormComponent,
    PurchaseShipmentEditFormComponent,
    PurchaseShipmentOverviewPageComponent,
    PurchaseShipmentSummaryPanelComponent,
    PurchasInvoiceSummaryPanelComponent,
    ReceiptFormComponent,
    RepeatingPurchaseInvoiceFormComponent,
    RepeatingSalesInvoiceFormComponent,
    RepeatingSalesInvoicePanelEditComponent,
    RepeatingSalesInvoicePanelViewComponent,
    RequestForQuoteCreateFormComponent,
    RequestForQuoteEditFormComponent,
    RequestForQuoteListPageComponent,
    RequestForQuoteOverviewPageComponent,
    RequestForQuoteSummaryPanelComponent,
    RequestItemFormComponent,
    SalesInvoiceListPageComponent,
    SalesInvoiceSummaryPanelComponent,
    SalesOrderEditFormComponent,
    SalesOrderListPageComponent,
    SalesOrderSummaryPanelComponent,
    SalesTermFormComponent,
    SelectInternalOrganisationComponent,
    SerialisedItemCharacteristicListPageComponent,
    SerialisedItemCharacteristicTypeFormComponent,
    SerialisedItemSummaryPanelComponent,
    ShipmentItemFormComponent,
    ShipmentListPageComponent,
    SubContractorRelationshipFormComponent,
    SupplierOfferingFormComponent,
    SupplierRelationshipFormComponent,
    TaskAssignmentLinkComponent,
    TaskAssignmentListPageComponent,
    TelecommunicationsNumberCreateFormComponent,
    UnifiedGoodListPageComponent,
    UnifiedGoodSummaryPanelComponent,
    UserProfileFormComponent,
    UserProfileLinkComponent,
    WebAddressCreateFormComponent,
    WebAddressEditFormComponent,
    WorkEffortAssignmentRateFormComponent,
    WorkEffortInvoiceItemAssignmentFormComponent,
    WorkEffortPartyAssignmentFormComponent,
    WorkRequirementCreateFormComponent,
    WorkRequirementEditFormComponent,
    WorkRequirementOverviewPageComponent,
    WorkRequirementSummaryPanelComponent,
  ],
  imports: [
    BrowserModule,
    NoopAnimationsModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatPaginatorModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTabsModule,
    MatTableModule,
    MatToolbarModule,
  ],
})
export class AppModule {}
