import { Composite } from '@allors/system/workspace/meta';
import {
  FormService,
  WorkspaceService,
} from '@allors/base/workspace/angular/foundation';

import { Injectable } from '@angular/core';
import {
  BankAccountFormComponent,
  BasepriceFormComponent,
  CarrierFormComponent,
  CustomerRelationshipFormComponent,
  CustomerShipmentCreateFormComponent,
  CustomerShipmentEditFormComponent,
  DisbursementFormComponent,
  EmailAddressCreateFormComponent,
  EmailAddressEditFormComponent,
  EmailCommunicationFormComponent,
  EmailMessageFormComponent,
  EmploymentFormComponent,
  ExchangeRateFormComponent,
  FaceToFaceCommunicationFormComponent,
  InventoryItemTransactionCreateFormComponent,
  LetterCorrespondenceFormComponent,
  ModelFormComponent,
  NonUnifiedGoodCreateFormComponent,
  NonUnifiedGoodEditFormComponent,
  OrderAdjustmentFormComponent,
  OrganisationContactRelationshipFormComponent,
  PartCategoryFormComponent,
  PartyContactmechanismFormComponent,
  PartyRateFormComponent,
  PhoneCommunicationFormComponent,
  PositionTypeFormComponent,
  PositionTypeRateFormComponent,
  PostalAddressCreateFormComponent,
  PostalAddressEditFormComponent,
  ProductIdentificationFormComponent,
  ProductQuoteApprovalFormComponent,
  ProductQuoteEditFormComponent,
  ProductTypeFormComponent,
  PurchaseInvoiceApprovalFormComponent,
  PurchaseInvoiceCreateFormComponent,
  PurchaseInvoiceEditFormComponent,
  PurchaseOrderApprovalLevel1FormComponent,
  PurchaseOrderApprovalLevel2FormComponent,
  PurchaseOrderEditFormComponent,
  PurchaseReturnCreateFormComponent,
  PurchaseReturnEditFormComponent,
  PurchaseShipmentCreateFormComponent,
  PurchaseShipmentEditFormComponent,
  ReceiptFormComponent,
  RepeatingPurchaseInvoiceFormComponent,
  RepeatingSalesInvoiceFormComponent,
  RequestForQuoteCreateFormComponent,
  RequestForQuoteEditFormComponent,
  RequestItemFormComponent,
  SalesOrderEditFormComponent,
  SalesTermFormComponent,
  SerialisedItemCharacteristicTypeFormComponent,
  ShipmentItemFormComponent,
  SubContractorRelationshipFormComponent,
  SupplierOfferingFormComponent,
  SupplierRelationshipFormComponent,
  TelecommunicationsNumberCreateFormComponent,
  TelecommunicationsNumberEditFormComponent,
  UserProfileFormComponent,
  WebAddressCreateFormComponent,
  WebAddressEditFormComponent,
  WorkEffortAssignmentRateFormComponent,
  WorkEffortInvoiceItemAssignmentFormComponent,
  WorkEffortPartyAssignmentFormComponent,
  WorkRequirementCreateFormComponent,
  WorkRequirementEditFormComponent,
} from '@allors/apps-intranet/workspace/angular-material';
import {
  BrandFormComponent,
  CatalogueFormComponent,
  FacilityFormComponent,
  MaintenanceAgreementCreateFormComponent,
  MaintenanceAgreementEditFormComponent,
  NonSerialisedInventoryItemFormComponent,
  NonUnifiedPartCreateFormComponent,
  NonUnifiedPartEditFormComponent,
  OperatingHoursTransactionFormComponent,
  OrganisationCreateFormComponent,
  OrganisationEditFormComponent,
  PersonFormComponent,
  ProductCategoryFormComponent,
  ProductQuoteCreateFormComponent,
  PurchaseInvoiceItemFormComponent,
  PurchaseOrderCreateFormComponent,
  PurchaseOrderItemFormComponent,
  QuoteItemFormComponent,
  SalesInvoiceCreateFormComponent,
  SalesInvoiceEditFormComponent,
  SalesInvoiceItemFormComponent,
  SalesOrderCreateFormComponent,
  SalesOrderItemFormComponent,
  SerialisedInventoryItemFormComponent,
  SerialisedItemCreateFormComponent,
  SerialisedItemEditFormComponent,
  SettingsFormComponent,
  TimeEntryFormComponent,
  UnifiedGoodCreateFormComponent,
  UnifiedGoodEditFormComponent,
  VehicleFormComponent,
  WorkEffortFixedAssetAssignmentFormComponent,
  WorkEffortInventoryAssignmentFormComponent,
  WorkEffortPartStandardFormComponent,
  WorkEffortPurchaseOrderItemAssignmentFormComponent,
  WorkEffortTypeCreateFormComponent,
  WorkEffortTypeEditFormComponent,
  WorkRequirementFulfillmentCreateFormComponent,
  WorkTaskCreateFormComponent,
  WorkTaskEditFormComponent,
} from '@allors/aviation-intranet/workspace/angular-material';
import { M } from '@allors/default/workspace/meta';

@Injectable()
export class AppFormService implements FormService {
  createFormByObjectType: Map<Composite, unknown>;
  editFormByObjectType: Map<Composite, unknown>;
  formByObjectType: Map<Composite, unknown>;

  constructor(workspaceService: WorkspaceService) {
    const m = workspaceService.workspace.configuration.metaPopulation as M;

    this.createFormByObjectType = new Map<Composite, unknown>([
      [m.CustomerShipment, CustomerShipmentCreateFormComponent],
      [m.EmailAddress, EmailAddressCreateFormComponent],
      [m.InventoryItemTransaction, InventoryItemTransactionCreateFormComponent],
      [m.MaintenanceAgreement, MaintenanceAgreementCreateFormComponent],
      [m.NonUnifiedGood, NonUnifiedGoodCreateFormComponent],
      [m.NonUnifiedPart, NonUnifiedPartCreateFormComponent],
      [m.Organisation, OrganisationCreateFormComponent],
      [m.PostalAddress, PostalAddressCreateFormComponent],
      [m.ProductQuote, ProductQuoteCreateFormComponent],
      [m.PurchaseInvoice, PurchaseInvoiceCreateFormComponent],
      [m.PurchaseOrder, PurchaseOrderCreateFormComponent],
      [m.PurchaseReturn, PurchaseReturnCreateFormComponent],
      [m.PurchaseShipment, PurchaseShipmentCreateFormComponent],
      [m.RequestForQuote, RequestForQuoteCreateFormComponent],
      [m.SalesInvoice, SalesInvoiceCreateFormComponent],
      [m.SalesOrder, SalesOrderCreateFormComponent],
      [m.SerialisedItem, SerialisedItemCreateFormComponent],
      [m.TelecommunicationsNumber, TelecommunicationsNumberCreateFormComponent],
      [m.UnifiedGood, UnifiedGoodCreateFormComponent],
      [m.WebAddress, WebAddressCreateFormComponent],
      [m.WorkEffortType, WorkEffortTypeCreateFormComponent],
      [m.WorkRequirement, WorkRequirementCreateFormComponent],
      [
        m.WorkRequirementFulfillment,
        WorkRequirementFulfillmentCreateFormComponent,
      ],
      [m.WorkTask, WorkTaskCreateFormComponent],
    ]);

    this.editFormByObjectType = new Map<Composite, unknown>([
      [m.CustomerShipment, CustomerShipmentEditFormComponent],
      [m.EmailAddress, EmailAddressEditFormComponent],
      [m.EmailMessage, EmailMessageFormComponent],
      [m.MaintenanceAgreement, MaintenanceAgreementEditFormComponent],
      [m.NonUnifiedGood, NonUnifiedGoodEditFormComponent],
      [m.NonUnifiedPart, NonUnifiedPartEditFormComponent],
      [m.Organisation, OrganisationEditFormComponent],
      [m.PostalAddress, PostalAddressEditFormComponent],
      [m.ProductQuote, ProductQuoteEditFormComponent],
      [m.PurchaseInvoice, PurchaseInvoiceEditFormComponent],
      [m.PurchaseOrder, PurchaseOrderEditFormComponent],
      [m.PurchaseReturn, PurchaseReturnEditFormComponent],
      [m.PurchaseShipment, PurchaseShipmentEditFormComponent],
      [m.RequestForQuote, RequestForQuoteEditFormComponent],
      [m.SalesInvoice, SalesInvoiceEditFormComponent],
      [m.SalesOrder, SalesOrderEditFormComponent],
      [m.SerialisedItem, SerialisedItemEditFormComponent],
      [m.TelecommunicationsNumber, TelecommunicationsNumberEditFormComponent],
      [m.UnifiedGood, UnifiedGoodEditFormComponent],
      [m.WebAddress, WebAddressEditFormComponent],
      [m.WorkEffortType, WorkEffortTypeEditFormComponent],
      [m.WorkRequirement, WorkRequirementEditFormComponent],
      // TODO:
      // [
      //   m.WorkRequirementFulfillment,
      //   WorkRequirementFulfillmentEditFormComponent,
      // ],
      [m.WorkTask, WorkTaskEditFormComponent],
    ]);

    this.formByObjectType = new Map<Composite, unknown>([
      [m.BankAccount, BankAccountFormComponent],
      [m.BasePrice, BasepriceFormComponent],
      [m.Brand, BrandFormComponent],
      [m.Carrier, CarrierFormComponent],
      [m.Catalogue, CatalogueFormComponent],
      [m.CustomerRelationship, CustomerRelationshipFormComponent],
      [m.Disbursement, DisbursementFormComponent],
      [m.EanIdentification, ProductIdentificationFormComponent],
      [m.EmailCommunication, EmailCommunicationFormComponent],
      [m.Employment, EmploymentFormComponent],
      [m.ExchangeRate, ExchangeRateFormComponent],
      [m.FaceToFaceCommunication, FaceToFaceCommunicationFormComponent],
      [m.Facility, FacilityFormComponent],
      [m.IncoTerm, SalesTermFormComponent],
      [m.IsbnIdentification, ProductIdentificationFormComponent],
      [m.InvoiceTerm, SalesTermFormComponent],
      [m.LetterCorrespondence, LetterCorrespondenceFormComponent],
      [m.ManufacturerIdentification, ProductIdentificationFormComponent],
      [m.Model, ModelFormComponent],
      [m.NonSerialisedInventoryItem, NonSerialisedInventoryItemFormComponent],
      [m.OperatingHoursTransaction, OperatingHoursTransactionFormComponent],
      // OrderAdjustment - begin
      [m.MiscellaneousCharge, OrderAdjustmentFormComponent],
      [m.DiscountAdjustment, OrderAdjustmentFormComponent],
      [m.ShippingAndHandlingCharge, OrderAdjustmentFormComponent],
      [m.Fee, OrderAdjustmentFormComponent],
      [m.SurchargeAdjustment, OrderAdjustmentFormComponent],
      // OrderAdjustment - end
      [m.OrderTerm, SalesTermFormComponent],
      [
        m.OrganisationContactRelationship,
        OrganisationContactRelationshipFormComponent,
      ],
      [m.PartCategory, PartCategoryFormComponent],
      [m.PartNumber, ProductIdentificationFormComponent],
      [m.PartyContactMechanism, PartyContactmechanismFormComponent],
      [m.PartyRate, PartyRateFormComponent],
      [m.PhoneCommunication, PhoneCommunicationFormComponent],
      [m.Person, PersonFormComponent],
      [m.PositionType, PositionTypeFormComponent],
      [m.PositionTypeRate, PositionTypeRateFormComponent],
      [m.ProductCategory, ProductCategoryFormComponent],
      [m.ProductNumber, ProductIdentificationFormComponent],
      [m.ProductQuoteApproval, ProductQuoteApprovalFormComponent],
      [m.ProductType, ProductTypeFormComponent],
      [m.PurchaseInvoiceApproval, PurchaseInvoiceApprovalFormComponent],
      [m.PurchaseInvoiceItem, PurchaseInvoiceItemFormComponent],
      [m.PurchaseOrderApprovalLevel1, PurchaseOrderApprovalLevel1FormComponent],
      [m.PurchaseOrderApprovalLevel2, PurchaseOrderApprovalLevel2FormComponent],
      [m.PurchaseOrderItem, PurchaseOrderItemFormComponent],
      [m.QuoteItem, QuoteItemFormComponent],
      [m.Receipt, ReceiptFormComponent],
      [m.RepeatingPurchaseInvoice, RepeatingPurchaseInvoiceFormComponent],
      [m.RepeatingSalesInvoice, RepeatingSalesInvoiceFormComponent],
      [m.RequestItem, RequestItemFormComponent],
      [m.SalesInvoiceItem, SalesInvoiceItemFormComponent],
      [m.SalesOrderItem, SalesOrderItemFormComponent],
      [m.SerialisedInventoryItem, SerialisedInventoryItemFormComponent],
      [
        m.SerialisedItemCharacteristicType,
        SerialisedItemCharacteristicTypeFormComponent,
      ],
      [m.Settings, SettingsFormComponent],
      [m.ShipmentItem, ShipmentItemFormComponent],
      [m.SkuIdentification, ProductIdentificationFormComponent],
      [m.SubContractorRelationship, SubContractorRelationshipFormComponent],
      [m.SupplierOffering, SupplierOfferingFormComponent],
      [m.SupplierRelationship, SupplierRelationshipFormComponent],
      [m.TimeEntry, TimeEntryFormComponent],
      [m.UpcaIdentification, ProductIdentificationFormComponent],
      [m.UpceIdentification, ProductIdentificationFormComponent],
      [m.UserProfile, UserProfileFormComponent],
      [m.Vehicle, VehicleFormComponent],
      [m.WorkEffortAssignmentRate, WorkEffortAssignmentRateFormComponent],
      [
        m.WorkEffortFixedAssetAssignment,
        WorkEffortFixedAssetAssignmentFormComponent,
      ],
      [
        m.WorkEffortInventoryAssignment,
        WorkEffortInventoryAssignmentFormComponent,
      ],
      [
        m.WorkEffortInvoiceItemAssignment,
        WorkEffortInvoiceItemAssignmentFormComponent,
      ],
      [m.WorkEffortPartStandard, WorkEffortPartStandardFormComponent],
      [m.WorkEffortPartyAssignment, WorkEffortPartyAssignmentFormComponent],
      [
        m.WorkEffortPurchaseOrderItemAssignment,
        WorkEffortPurchaseOrderItemAssignmentFormComponent,
      ],
    ]);
  }

  createForm(objectType: Composite) {
    return (
      this.createFormByObjectType.get(objectType) ??
      this.formByObjectType.get(objectType)
    );
  }

  editForm(objectType: Composite) {
    return (
      this.editFormByObjectType.get(objectType) ??
      this.formByObjectType.get(objectType)
    );
  }
}

export const createComponents: any[] = [
  CustomerShipmentCreateFormComponent,
  EmailAddressCreateFormComponent,
  MaintenanceAgreementCreateFormComponent,
  NonUnifiedGoodCreateFormComponent,
  NonUnifiedPartCreateFormComponent,
  OrganisationCreateFormComponent,
  PostalAddressCreateFormComponent,
  ProductQuoteCreateFormComponent,
  PurchaseInvoiceCreateFormComponent,
  PurchaseOrderCreateFormComponent,
  PurchaseReturnCreateFormComponent,
  PurchaseShipmentCreateFormComponent,
  RequestForQuoteCreateFormComponent,
  SalesInvoiceCreateFormComponent,
  SalesOrderCreateFormComponent,
  SerialisedItemCreateFormComponent,
  TelecommunicationsNumberCreateFormComponent,
  UnifiedGoodCreateFormComponent,
  WebAddressCreateFormComponent,
  WorkEffortTypeCreateFormComponent,
  WorkRequirementCreateFormComponent,
  WorkRequirementFulfillmentCreateFormComponent,
  WorkTaskCreateFormComponent,
];

export const editComponents: any[] = [
  CustomerShipmentEditFormComponent,
  EmailAddressEditFormComponent,
  EmailMessageFormComponent,
  MaintenanceAgreementEditFormComponent,
  NonUnifiedGoodEditFormComponent,
  NonUnifiedPartEditFormComponent,
  OrganisationEditFormComponent,
  PostalAddressEditFormComponent,
  ProductQuoteEditFormComponent,
  PurchaseInvoiceEditFormComponent,
  PurchaseOrderEditFormComponent,
  PurchaseReturnEditFormComponent,
  PurchaseShipmentEditFormComponent,
  RequestForQuoteEditFormComponent,
  SalesInvoiceEditFormComponent,
  SalesOrderEditFormComponent,
  SerialisedItemEditFormComponent,
  TelecommunicationsNumberEditFormComponent,
  UnifiedGoodEditFormComponent,
  WebAddressEditFormComponent,
  WorkEffortTypeEditFormComponent,
  WorkRequirementEditFormComponent,
  // TODO:
  // WorkRequirementFulfillmentEditFormComponent,
  WorkTaskEditFormComponent,
];

export const components: any[] = [
  BankAccountFormComponent,
  BasepriceFormComponent,
  BrandFormComponent,
  CarrierFormComponent,
  CatalogueFormComponent,
  CustomerRelationshipFormComponent,
  DisbursementFormComponent,
  EmailCommunicationFormComponent,
  EmploymentFormComponent,
  ExchangeRateFormComponent,
  FaceToFaceCommunicationFormComponent,
  FacilityFormComponent,
  InventoryItemTransactionCreateFormComponent,
  LetterCorrespondenceFormComponent,
  ModelFormComponent,
  NonSerialisedInventoryItemFormComponent,
  OperatingHoursTransactionFormComponent,
  OrderAdjustmentFormComponent,
  OrganisationContactRelationshipFormComponent,
  PersonFormComponent,
  PartCategoryFormComponent,
  PartyContactmechanismFormComponent,
  PartyRateFormComponent,
  PhoneCommunicationFormComponent,
  PositionTypeFormComponent,
  PositionTypeRateFormComponent,
  ProductCategoryFormComponent,
  ProductIdentificationFormComponent,
  ProductQuoteApprovalFormComponent,
  ProductTypeFormComponent,
  PurchaseInvoiceApprovalFormComponent,
  PurchaseInvoiceItemFormComponent,
  PurchaseOrderApprovalLevel1FormComponent,
  PurchaseOrderApprovalLevel2FormComponent,
  PurchaseOrderItemFormComponent,
  QuoteItemFormComponent,
  ReceiptFormComponent,
  RepeatingPurchaseInvoiceFormComponent,
  RepeatingSalesInvoiceFormComponent,
  RequestItemFormComponent,
  SalesInvoiceItemFormComponent,
  SalesOrderItemFormComponent,
  SalesTermFormComponent,
  SerialisedInventoryItemFormComponent,
  SerialisedItemCharacteristicTypeFormComponent,
  SettingsFormComponent,
  ShipmentItemFormComponent,
  SubContractorRelationshipFormComponent,
  SupplierOfferingFormComponent,
  SupplierRelationshipFormComponent,
  TimeEntryFormComponent,
  UserProfileFormComponent,
  VehicleFormComponent,
  WorkEffortAssignmentRateFormComponent,
  WorkEffortFixedAssetAssignmentFormComponent,
  WorkEffortInventoryAssignmentFormComponent,
  WorkEffortInvoiceItemAssignmentFormComponent,
  WorkEffortPartStandardFormComponent,
  WorkEffortPartyAssignmentFormComponent,
  WorkEffortPurchaseOrderItemAssignmentFormComponent,
];
